apiVersion: v1
kind: Service
metadata:
  name: sb-api
  namespace: secondbrain-os
  labels:
    app: sb-api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http-api
  selector:
    app: sb-api
