apiVersion: v1
kind: Service
metadata:
  name: sb-web
  namespace: secondbrain-os
  labels:
    app: sb-web
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http-web
  selector:
    app: sb-web
