apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-web
  namespace: secondbrain-os
  labels:
    app: sb-web
    tier: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: sb-web
  template:
    metadata:
      labels:
        app: sb-web
    spec:
      containers:
        - name: web
          image: ghcr.io/secondbrain-os/web:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: sb-config
            - secretRef:
                name: sb-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
