apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: secondbrain
  labels:
    app: web
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http-web
  selector:
    app: web
