#!/usr/bin/env python3
"""Skill Database Architecture — Full Generator Script.

Generates the complete skills database from the SDB architecture spec.
Usage: python gen_sdb_full.py [--migrations-dir MIGRATIONS_DIR] [--output OUTPUT]
"""

import argparse
import os
import sys
from pathlib import Path


MIGRATIONS = [
    "000_skills_complete_ddl.sql",
    "001_skills_core_taxonomy.sql",
    "002_skills_user_tables.sql",
    "003_skills_intelligence_supporting.sql",
    "004_skills_audit_events_analytics.sql",
    "005_skills_security_rls.sql",
    "006_skills_materialized_views.sql",
    "007_skills_partman_cron.sql",
]


def validate_migrations(migrations_dir: Path) -> dict:
    """Validate all migration files exist and return metadata."""
    result = {"present": [], "missing": [], "sizes": {}}
    for fname in MIGRATIONS:
        fpath = migrations_dir / fname
        if fpath.exists():
            size = fpath.stat().st_size
            result["present"].append(fname)
            result["sizes"][fname] = size
        else:
            result["missing"].append(fname)
    return result


def build_aggregate_ddl(migrations_dir: Path) -> str:
    """Concatenate all migration files into a single DDL script."""
    parts = []
    parts.append("-- =============================================================")
    parts.append("-- SKILLS DATABASE — AUTO-GENERATED AGGREGATE DDL")
    parts.append(f"-- Generated: {__import__('datetime').datetime.now().isoformat()}")
    parts.append("-- Source: gen_sdb_full.py")
    parts.append("-- =============================================================")
    parts.append("")
    for fname in MIGRATIONS:
        fpath = migrations_dir / fname
        if fpath.exists():
            content = fpath.read_text(encoding="utf-8")
            parts.append(f"-- ===== Begin: {fname} =====")
            parts.append(content)
            parts.append(f"-- ===== End: {fname} =====")
            parts.append("")
    return "\n".join(parts)


def generate_python_schemas(output_dir: Path):
    """Generate Pydantic model stubs from migration analysis."""
    schemas_path = output_dir / "schemas_generated.py"
    content = """# Auto-generated Pydantic schemas from SDB architecture
# Generated by gen_sdb_full.py
from pydantic import BaseModel
from typing import Optional
from enum import Enum


class AuditAction(str, Enum):
    insert = "INSERT"
    update = "UPDATE"
    delete = "DELETE"
    soft_delete = "SOFT_DELETE"
    restore = "RESTORE"


class EventOutboxStatus(str, Enum):
    pending = "pending"
    processing = "processing"
    delivered = "delivered"
    failed = "failed"
    dead_letter = "dead_letter"


class WebhookStatus(str, Enum):
    pending = "pending"
    delivering = "delivering"
    delivered = "delivered"
    failed = "failed"
    dead_letter = "dead_letter"


class SubscriptionStatus(str, Enum):
    active = "active"
    paused = "paused"
    disabled = "disabled"


class ForecastMetric(str, Enum):
    demand = "demand"
    growth = "growth"
    salary = "salary"
    competition = "competition"
    future_relevance = "future_relevance"
    skill_health = "skill_health"
    avg_skill_level = "avg_skill_level"
    skill_count = "skill_count"
    readiness_score = "readiness_score"
    learning_velocity = "learning_velocity"
    income_potential = "income_potential"
    emerging_coverage = "emerging_coverage"


class ForecastScope(str, Enum):
    individual = "individual"
    organization = "organization"
    global_ = "global"


class ForecastModel(str, Enum):
    linear = "linear"
    holt_winters = "holt_winters"
    arima = "arima"
    bass_diffusion = "bass_diffusion"
    ensemble = "ensemble"


# === Audit Log Models ===
class SkillAuditLogCreate(BaseModel):
    table_name: str
    record_id: str
    user_id: Optional[str] = None
    action: AuditAction
    old_data: Optional[dict] = None
    new_data: Optional[dict] = None
    changed_fields: Optional[list[str]] = None
    change_reason: Optional[str] = None
    ip_address: Optional[str] = None
    user_agent: Optional[str] = None
    request_id: Optional[str] = None


class SkillAuditLogResponse(SkillAuditLogCreate):
    audit_id: str
    created_at: int

    class Config:
        from_attributes = True


# === Event Subscription Models ===
class SkillEventSubscriptionCreate(BaseModel):
    name: str
    url: str
    event_types: list[str] = []
    headers: dict = {}
    is_active: bool = True
    retry_policy: dict = {"max_retries": 5, "backoff": "exponential", "initial_delay_ms": 1000}


class SkillEventSubscriptionUpdate(BaseModel):
    name: Optional[str] = None
    url: Optional[str] = None
    event_types: Optional[list[str]] = None
    headers: Optional[dict] = None
    is_active: Optional[bool] = None
    retry_policy: Optional[dict] = None


class SkillEventSubscriptionResponse(SkillEventSubscriptionCreate):
    subscription_id: str
    last_delivered_at: Optional[int] = None
    last_error_at: Optional[int] = None
    delivery_count: int = 0
    failure_count: int = 0
    created_at: int
    updated_at: int

    class Config:
        from_attributes = True


# === Event Outbox Models ===
class SkillEventOutboxCreate(BaseModel):
    event_type: str
    aggregate_type: str
    aggregate_id: str
    payload: dict
    headers: dict = {}


class SkillEventOutboxResponse(SkillEventOutboxCreate):
    outbox_id: str
    status: EventOutboxStatus
    retry_count: int = 0
    max_retries: int = 3
    last_error: Optional[str] = None
    scheduled_at: Optional[int] = None
    processed_at: Optional[int] = None
    created_at: int

    class Config:
        from_attributes = True


# === Webhook Queue Models ===
class SkillWebhookQueueResponse(BaseModel):
    webhook_id: str
    subscription_id: str
    event_type: str
    payload: dict
    url: str
    headers: dict = {}
    status: WebhookStatus
    retry_count: int = 0
    max_retries: int = 5
    last_error: Optional[str] = None
    last_http_status: Optional[int] = None
    scheduled_at: Optional[int] = None
    delivered_at: Optional[int] = None
    created_at: int

    class Config:
        from_attributes = True


# === Skill Event Models ===
class SkillEventCreate(BaseModel):
    event_type: str
    event_version: str = "1.0"
    aggregate_type: str
    aggregate_id: str
    user_id: Optional[str] = None
    data: dict
    metadata: dict = {}
    correlation_id: Optional[str] = None
    causation_id: Optional[str] = None


class SkillEventResponse(SkillEventCreate):
    event_id: str
    created_at: int

    class Config:
        from_attributes = True


# === Analytics Snapshot Models ===
class SkillAnalyticsSnapshotCreate(BaseModel):
    user_id: str
    snapshot_date: str
    avg_skill_level: Optional[float] = None
    skill_count: Optional[int] = None
    readiness_score: Optional[float] = None
    learning_velocity: Optional[float] = None
    diversification_score: Optional[float] = None
    income_per_hour: Optional[float] = None
    market_alignment: Optional[float] = None
    emerging_coverage: Optional[int] = None
    milestone_completion: Optional[float] = None
    evidence_ratio: Optional[float] = None
    metadata: dict = {}


class SkillAnalyticsSnapshotResponse(SkillAnalyticsSnapshotCreate):
    snapshot_id: str
    created_at: int

    class Config:
        from_attributes = True


# === Forecast Models ===
class SkillForecastCreate(BaseModel):
    skill_id: str
    metric: ForecastMetric
    forecast_date: str
    predicted_value: float
    confidence_lower: Optional[float] = None
    confidence_upper: Optional[float] = None
    model_version: str = "1.0"


class SkillForecastResponse(SkillForecastCreate):
    forecast_id: str
    metadata: dict = {}
    created_at: int

    class Config:
        from_attributes = True


# === Skill Taxonomy History Models ===
class SkillTaxonomyHistoryCreate(BaseModel):
    entity_type: str
    entity_id: str
    version: int
    previous_state: dict
    new_state: dict
    change_type: str
    changed_by: Optional[str] = None
    change_reason: Optional[str] = None


class SkillTaxonomyHistoryResponse(SkillTaxonomyHistoryCreate):
    history_id: str
    created_at: int

    class Config:
        from_attributes = True


# === User Skill History Models ===
class SkillUserSkillHistoryCreate(BaseModel):
    user_id: str
    skill_id: str
    version: int
    proficiency_before: Optional[int] = None
    proficiency_after: Optional[int] = None
    hours_since_last: Optional[float] = None
    change_type: str
    changed_by: Optional[str] = None


class SkillUserSkillHistoryResponse(SkillUserSkillHistoryCreate):
    history_id: str
    created_at: int

    class Config:
        from_attributes = True


# === Market History Models ===
class SkillMarketHistoryCreate(BaseModel):
    skill_id: str
    demand_score: Optional[int] = None
    growth_score: Optional[float] = None
    salary_median: Optional[int] = None
    competition_score: Optional[int] = None
    future_relevance: Optional[float] = None
    skill_health: Optional[float] = None
    snapshot_source: str = "automated"


class SkillMarketHistoryResponse(SkillMarketHistoryCreate):
    market_history_id: str
    created_at: int

    class Config:
        from_attributes = True


# === Roadmap Definition Models ===
class SkillRoadmapDefinitionCreate(BaseModel):
    name: str
    description: str = ""
    target_skill_id: Optional[str] = None
    difficulty: str = "intermediate"
    estimated_duration: Optional[str] = None
    is_ai_generated: bool = False


class SkillRoadmapDefinitionResponse(SkillRoadmapDefinitionCreate):
    roadmap_id: str
    created_at: int
    updated_at: int

    class Config:
        from_attributes = True
"""
    schemas_path.write_text(content, encoding="utf-8")
    return schemas_path


def generate_api_stubs(output_dir: Path):
    """Generate API endpoint stubs for missing routes."""
    stubs_path = output_dir / "api_stubs_generated.py"
    content = '''"""Auto-generated API stubs for missing skill endpoints.
Append these route functions to apps/api/app/api/skills.py.
"""

# ==================== Audit Log Endpoints ====================

@router.get("/audit-log", response_model=List[SkillAuditLogResponse])
async def list_audit_log(
    current_user=Depends(get_current_user),
    table_name: str = Query(None),
    record_id: str = Query(None),
    limit: int = Query(50, ge=1, le=500),
    offset: int = Query(0, ge=0),
):
    supabase = _get_supabase()
    query = supabase.from_("skill_audit_log").select("*").range(offset, offset + limit - 1).order("created_at", desc=True)
    if table_name:
        query = query.eq("table_name", table_name)
    if record_id:
        query = query.eq("record_id", record_id)
    response = query.execute()
    return response.data


@router.get("/audit-log/{audit_id}", response_model=SkillAuditLogResponse)
async def get_audit_entry(audit_id: str, current_user=Depends(get_current_user)):
    supabase = _get_supabase()
    response = supabase.from_("skill_audit_log").select("*").eq("audit_id", audit_id).execute()
    if not response.data:
        raise HTTPException(status_code=404, detail="Audit entry not found")
    return response.data[0]


@router.get("/audit-log/table/{table_name}/record/{record_id}", response_model=List[SkillAuditLogResponse])
async def get_audit_for_record(table_name: str, record_id: str, current_user=Depends(get_current_user)):
    supabase = _get_supabase()
    response = supabase.from_("skill_audit_log").select("*").eq("table_name", table_name).eq("record_id", record_id).order("created_at", desc=True).execute()
    return response.data


# ==================== Event Subscription Endpoints ====================

@router.get("/event-subscriptions", response_model=List[SkillEventSubscriptionResponse])
async def list_event_subscriptions(
    current_user=Depends(get_current_user),
    is_active: bool = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
):
    supabase = _get_supabase()
    query = supabase.from_("skill_event_subscriptions").select("*").range(offset, offset + limit - 1).order("name")
    if is_active is not None:
        query = query.eq("is_active", is_active)
    response = query.execute()
    return response.data


@router.post("/event-subscriptions", status_code=201, response_model=SkillEventSubscriptionResponse)
async def create_event_subscription(sub: SkillEventSubscriptionCreate, current_user=Depends(get_current_user)):
    supabase = _get_supabase()
    data = sub.model_dump()
    response = supabase.from_("skill_event_subscriptions").insert(data).execute()
    if response.error:
        raise HTTPException(status_code=400, detail=response.error.message)
    return response.data[0]


@router.get("/event-subscriptions/{subscription_id}", response_model=SkillEventSubscriptionResponse)
async def get_event_subscription(subscription_id: str, current_user=Depends(get_current_user)):
    supabase = _get_supabase()
    response = supabase.from_("skill_event_subscriptions").select("*").eq("subscription_id", subscription_id).execute()
    if not response.data:
        raise HTTPException(status_code=404, detail="Subscription not found")
    return response.data[0]


@router.put("/event-subscriptions/{subscription_id}", response_model=SkillEventSubscriptionResponse)
async def update_event_subscription(subscription_id: str, update: SkillEventSubscriptionUpdate, current_user=Depends(get_current_user)):
    supabase = _get_supabase()
    update_data = {k: v for k, v in update.model_dump().items() if v is not None}
    response = supabase.from_("skill_event_subscriptions").update(update_data).eq("subscription_id", subscription_id).execute()
    if not response.data:
        raise HTTPException(status_code=404, detail="Subscription not found")
    return response.data[0]


@router.delete("/event-subscriptions/{subscription_id}", status_code=204)
async def delete_event_subscription(subscription_id: str, current_user=Depends(get_current_user)):
    supabase = _get_supabase()
    response = supabase.from_("skill_event_subscriptions").delete().eq("subscription_id", subscription_id).execute()
    return None


# ==================== Event Endpoints ====================

@router.get("/events", response_model=List[SkillEventResponse])
async def list_events(
    current_user=Depends(get_current_user),
    event_type: str = Query(None),
    aggregate_type: str = Query(None),
    aggregate_id: str = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
):
    supabase = _get_supabase()
    query = supabase.from_("skill_events").select("*").range(offset, offset + limit - 1).order("created_at", desc=True)
    if event_type:
        query = query.eq("event_type", event_type)
    if aggregate_type:
        query = query.eq("aggregate_type", aggregate_type)
    if aggregate_id:
        query = query.eq("aggregate_id", aggregate_id)
    response = query.execute()
    return response.data


@router.get("/events/{event_id}", response_model=SkillEventResponse)
async def get_event(event_id: str, current_user=Depends(get_current_user)):
    supabase = _get_supabase()
    response = supabase.from_("skill_events").select("*").eq("event_id", event_id).execute()
    if not response.data:
        raise HTTPException(status_code=404, detail="Event not found")
    return response.data[0]


# ==================== Analytics Snapshot Endpoints ====================

@router.get("/analytics-snapshots", response_model=List[SkillAnalyticsSnapshotResponse])
async def list_analytics_snapshots(
    current_user=Depends(get_current_user),
    user_id: str = Query(None),
    from_date: str = Query(None),
    to_date: str = Query(None),
    limit: int = Query(100, ge=1, le=365),
    offset: int = Query(0, ge=0),
):
    supabase = _get_supabase()
    query = supabase.from_("skill_analytics_snapshots").select("*").range(offset, offset + limit - 1).order("snapshot_date", desc=True)
    if user_id:
        query = query.eq("user_id", user_id)
    if from_date:
        query = query.gte("snapshot_date", from_date)
    if to_date:
        query = query.lte("snapshot_date", to_date)
    response = query.execute()
    return response.data


@router.get("/analytics-snapshots/latest", response_model=SkillAnalyticsSnapshotResponse)
async def get_latest_analytics_snapshot(current_user=Depends(get_current_user)):
    supabase = _get_supabase()
    user_id = current_user.user.id
    response = supabase.from_("skill_analytics_snapshots").select("*").eq("user_id", user_id).order("snapshot_date", desc=True).limit(1).execute()
    if not response.data:
        raise HTTPException(status_code=404, detail="No analytics snapshots found")
    return response.data[0]


@router.post("/analytics-snapshots/trigger-refresh", status_code=202)
async def trigger_analytics_refresh(current_user=Depends(get_current_user)):
    """Trigger an analytics snapshot refresh for the current user."""
    return {"status": "queued", "message": "Analytics refresh triggered"}


# ==================== Forecast Endpoints ====================

@router.get("/forecasts", response_model=List[SkillForecastResponse])
async def list_forecasts(
    current_user=Depends(get_current_user),
    skill_id: str = Query(None),
    metric: str = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
):
    supabase = _get_supabase()
    query = supabase.from_("skill_forecasts").select("*").range(offset, offset + limit - 1).order("forecast_date", desc=True)
    if skill_id:
        query = query.eq("skill_id", skill_id)
    if metric:
        query = query.eq("metric", metric)
    response = query.execute()
    return response.data


@router.post("/forecasts", status_code=201, response_model=SkillForecastResponse)
async def create_forecast(forecast: SkillForecastCreate, current_user=Depends(get_current_user)):
    supabase = _get_supabase()
    data = forecast.model_dump()
    response = supabase.from_("skill_forecasts").insert(data).execute()
    if response.error:
        raise HTTPException(status_code=400, detail=response.error.message)
    return response.data[0]


# ==================== Webhook Queue Endpoints (Admin) ====================

@router.get("/webhook-queue", response_model=List[SkillWebhookQueueResponse])
async def list_webhook_queue(
    current_user=Depends(get_current_user),
    status: str = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
):
    supabase = _get_supabase()
    query = supabase.from_("skill_webhook_queue").select("*").range(offset, offset + limit - 1).order("created_at", desc=True)
    if status:
        query = query.eq("status", status)
    response = query.execute()
    return response.data


# ==================== Taxonomy History Endpoints ====================

@router.get("/taxonomy-history", response_model=List[SkillTaxonomyHistoryResponse])
async def list_taxonomy_history(
    current_user=Depends(get_current_user),
    entity_type: str = Query(None),
    entity_id: str = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
):
    supabase = _get_supabase()
    query = supabase.from_("skill_taxonomy_history").select("*").range(offset, offset + limit - 1).order("created_at", desc=True)
    if entity_type:
        query = query.eq("entity_type", entity_type)
    if entity_id:
        query = query.eq("entity_id", entity_id)
    response = query.execute()
    return response.data


# ==================== User Skill History Endpoints ====================

@router.get("/user-skill-history", response_model=List[SkillUserSkillHistoryResponse])
async def list_user_skill_history(
    current_user=Depends(get_current_user),
    user_id: str = Query(None),
    skill_id: str = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
):
    supabase = _get_supabase()
    query = supabase.from_("skill_user_skill_history").select("*").range(offset, offset + limit - 1).order("created_at", desc=True)
    if user_id:
        query = query.eq("user_id", user_id)
    if skill_id:
        query = query.eq("skill_id", skill_id)
    response = query.execute()
    return response.data


# ==================== Market History Endpoints ====================

@router.get("/market-history", response_model=List[SkillMarketHistoryResponse])
async def list_market_history(
    current_user=Depends(get_current_user),
    skill_id: str = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
):
    supabase = _get_supabase()
    query = supabase.from_("skill_market_history").select("*").range(offset, offset + limit - 1).order("created_at", desc=True)
    if skill_id:
        query = query.eq("skill_id", skill_id)
    response = query.execute()
    return response.data


# ==================== Roadmap Definitions Endpoints ====================

@router.get("/roadmap-definitions", response_model=List[SkillRoadmapDefinitionResponse])
async def list_roadmap_definitions(
    current_user=Depends(get_current_user),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
):
    supabase = _get_supabase()
    response = supabase.from_("skill_roadmap_definitions").select("*").range(offset, offset + limit - 1).order("name").execute()
    return response.data


@router.post("/roadmap-definitions", status_code=201, response_model=SkillRoadmapDefinitionResponse)
async def create_roadmap_definition(defn: SkillRoadmapDefinitionCreate, current_user=Depends(get_current_user)):
    supabase = _get_supabase()
    data = defn.model_dump()
    response = supabase.from_("skill_roadmap_definitions").insert(data).execute()
    if response.error:
        raise HTTPException(status_code=400, detail=response.error.message)
    return response.data[0]


@router.get("/roadmap-definitions/{roadmap_id}", response_model=SkillRoadmapDefinitionResponse)
async def get_roadmap_definition(roadmap_id: str, current_user=Depends(get_current_user)):
    supabase = _get_supabase()
    response = supabase.from_("skill_roadmap_definitions").select("*").eq("roadmap_id", roadmap_id).execute()
    if not response.data:
        raise HTTPException(status_code=404, detail="Roadmap definition not found")
    return response.data[0]


# ==================== Materialized View Endpoints ====================

@router.post("/materialized-views/refresh", status_code=202)
async def refresh_all_views(current_user=Depends(get_current_user)):
    """Trigger refresh of all materialized views."""
    return {"status": "queued", "message": "Materialized view refresh triggered"}


@router.get("/materialized-views/user-proficiency", response_model=List)
async def get_user_proficiency(current_user=Depends(get_current_user)):
    supabase = _get_supabase()
    user_id = current_user.user.id
    response = supabase.from_("mv_skill_user_proficiency").select("*").eq("user_id", user_id).execute()
    return response.data


@router.get("/materialized-views/market-intelligence", response_model=List)
async def get_market_intelligence(current_user=Depends(get_current_user)):
    supabase = _get_supabase()
    response = supabase.from_("mv_skill_market_intelligence").select("*").order("skill_health", desc=True).limit(50).execute()
    return response.data
'''
    stubs_path.write_text(content, encoding="utf-8")
    return stubs_path


def main():
    parser = argparse.ArgumentParser(description="Generate the complete skills database from SDB architecture")
    parser.add_argument("--migrations-dir", default="scripts/migrations", help="Path to migration files")
    parser.add_argument("--output", default=None, help="Output file for aggregate DDL")
    parser.add_argument("--validate-only", action="store_true", help="Only validate migrations, don't generate")
    parser.add_argument("--generate-schemas", action="store_true", help="Generate Python Pydantic model stubs")
    parser.add_argument("--generate-api-stubs", action="store_true", help="Generate API endpoint stubs")
    args = parser.parse_args()

    migrations_dir = Path(args.migrations_dir)

    if not migrations_dir.exists():
        print(f"Error: migrations directory not found: {migrations_dir}", file=sys.stderr)
        sys.exit(1)

    status = validate_migrations(migrations_dir)

    print(f"=== Skill Database Architecture Generator ===")
    print(f"Migrations dir: {migrations_dir.resolve()}")
    print(f"Present: {len(status['present'])}/{len(MIGRATIONS)}")
    print(f"Missing: {status['missing'] if status['missing'] else 'None'}")
    print()

    for fname in MIGRATIONS:
        if fname in status["sizes"]:
            size_kb = status["sizes"][fname] / 1024
            print(f"  {'[OK]' if fname in status['present'] else '[MISSING]'} {fname} ({size_kb:.1f} KB)")
        else:
            print(f"  [MISSING] {fname}")

    if args.validate_only:
        if status["missing"]:
            print(f"\nValidation FAILED: {len(status['missing'])} migration(s) missing")
            sys.exit(1)
        print("\nValidation PASSED: All migrations present")
        return

    if args.output:
        output_path = Path(args.output)
        aggregate = build_aggregate_ddl(migrations_dir)
        output_path.write_text(aggregate, encoding="utf-8")
        print(f"\nAggregate DDL written to: {output_path.resolve()} ({len(aggregate)} bytes)")

    if args.generate_schemas:
        out = Path("packages/database/schemas")
        out.mkdir(parents=True, exist_ok=True)
        path = generate_python_schemas(out)
        print(f"Generated schemas: {path}")

    if args.generate_api_stubs:
        out = Path("apps/api/app/api")
        out.mkdir(parents=True, exist_ok=True)
        path = generate_api_stubs(out)
        print(f"Generated API stubs: {path}")

    if not any([args.output, args.generate_schemas, args.generate_api_stubs]):
        print("\nNo output options specified. Use --output, --generate-schemas, or --generate-api-stubs.")


if __name__ == "__main__":
    main()
