import sys
import uuid
import logging
import time as _time
from pathlib import Path
from contextlib import asynccontextmanager

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "packages"))

import sentry_sdk
from sentry_sdk.integrations.fastapi import FastApiIntegration
from sentry_sdk.integrations.httpx import HttpxIntegration
from sentry_sdk.integrations.logging import LoggingIntegration

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import JSONResponse
from shared.utils.rate_limiter import RateLimiter
from shared.utils.csrf import CSRFMiddleware
from shared.utils.logger import logger, log_request, log_response
from shared.utils.cache import cache
from shared.utils.audit import audit_middleware_dispatch, MUTATION_METHODS
from config.core.config import settings
from app.api import (
    auth,
    tasks,
    courses,
    goals,
    ideas,
    chat,
    projects,
    resources,
    opportunities,
    income,
    habits,
    sleep,
    time,
    automation,
    briefings,
    reviews,
    memory,
    roadmap,
    academics,
    videos,
    analytics,
    predictions,
    notifications,
    nlp,
    prompts,
    feedback,
    monitoring,
    data_export,
    feature_flags,
    skills,
)


@asynccontextmanager
async def lifespan(application: FastAPI):
    import time
    application.state.start_time = time.time()
    logger.info(
        "Second Brain OS API starting",
        version=settings.app_version,
        environment=settings.environment,
        debug=settings.debug,
    )

    if settings.sentry_dsn:
        sentry_sdk.init(
            dsn=settings.sentry_dsn,
            environment=settings.environment,
            integrations=[
                FastApiIntegration(),
                HttpxIntegration(),
                LoggingIntegration(level=logging.INFO, event_level=logging.ERROR),
            ],
            traces_sample_rate=0.25,
            send_default_pii=False,
        )
        logger.info("Sentry initialized for backend")

    yield
    logger.info("Second Brain OS API shutting down")

    pending_tasks = getattr(application.state, "pending_ai_tasks", [])
    if pending_tasks:
        logger.info("Awaiting pending AI tasks", count=len(pending_tasks))
        import asyncio
        try:
            await asyncio.wait_for(asyncio.gather(*pending_tasks, return_exceptions=True), timeout=10)
        except asyncio.TimeoutError:
            logger.warn("Some AI tasks did not complete in time", count=len(pending_tasks))

    await cache.clear()
    logger.info("Second Brain OS API shutdown complete")


app = FastAPI(
    title="Second Brain OS API",
    description="Personal AI productivity system for BTech CSE students. "
    "15 modules covering tasks, courses, goals, habits, sleep, income, "
    "projects, ideas, resources, opportunities, time tracking, chat, and automation.",
    version=settings.app_version,
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_tags=[
        {"name": "tasks", "description": "Task CRUD with priority, status, dependencies"},
        {"name": "courses", "description": "Course tracking with progress, deadlines"},
        {"name": "goals", "description": "Goal management with roadmap, milestones"},
        {"name": "habits", "description": "Habit definitions with frequency, streaks"},
        {"name": "sleep", "description": "Sleep tracking with score, debt"},
        {"name": "income", "description": "Income logs with hourly rate"},
        {"name": "projects", "description": "Project phases, blockers, URLs"},
        {"name": "ideas", "description": "Idea pipeline (raw to validating to building)"},
        {"name": "resources", "description": "Resource library with tags"},
        {"name": "opportunities", "description": "Opportunity radar with match scores"},
        {"name": "time", "description": "Time tracking with Pomodoro, deep work"},
        {"name": "chat", "description": "AI chat with ARIA orchestrator"},
        {"name": "automation", "description": "One-click triggers for briefings, radar, reviews"},
        {"name": "briefings", "description": "Daily briefings generated by AI"},
        {"name": "reviews", "description": "Weekly reviews generated by AI"},
        {"name": "memory", "description": "AI persistent memory and preferences"},
        {"name": "roadmap", "description": "Skill development roadmap milestones"},
        {"name": "academics", "description": "Subject and marks tracking"},
        {"name": "videos", "description": "YouTube video vault"},
        {"name": "analytics", "description": "Aggregated productivity stats"},
        {"name": "predictions", "description": "ML-based completion and sleep predictions"},
        {"name": "notifications", "description": "Proactive nudges and alerts"},
        {"name": "nlp", "description": "Natural language command parsing"},
        {"name": "prompts", "description": "Prompt file inspection and rendering"},
        {"name": "feedback", "description": "User feedback collection and summary"},
        {"name": "monitoring", "description": "Token usage and cost tracking"},
        {"name": "auth", "description": "Authentication, token refresh, and API key rotation"},
        {"name": "data", "description": "GDPR data export and data management"},
        {"name": "skills", "description": "Skills taxonomy, user skills, evidence, market intelligence, and learning paths"},
        {"name": "system", "description": "Health check and system endpoints"},
    ],
)

app.add_middleware(
    RateLimiter,
    max_requests=settings.rate_limit_max,
    window_seconds=settings.rate_limit_window,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins.split(",") if settings.cors_origins else ["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.add_middleware(GZipMiddleware, minimum_size=1000)

app.add_middleware(CSRFMiddleware)


@app.middleware("http")
async def request_id_middleware(request: Request, call_next):
    request_id = request.headers.get("X-Request-ID", str(uuid.uuid4()))
    request.state.request_id = request_id
    request.state.start_time = _time.time()

    log_request(
        endpoint=str(request.url.path),
        method=request.method,
        request_id=request_id,
    )

    try:
        response = await call_next(request)
    except Exception as exc:
        duration_ms = (_time.time() - request.state.start_time) * 1000
        logger.error(
            "Unhandled request exception",
            path=str(request.url.path),
            method=request.method,
            duration_ms=duration_ms,
            request_id=request_id,
            error=str(exc),
        )
        from fastapi.responses import JSONResponse
        return JSONResponse(
            status_code=500,
            content={
                "detail": "Internal server error",
                "error_code": "INTERNAL_ERROR",
                "request_id": request_id,
                "timestamp": _time.time(),
            },
            headers={"X-Request-ID": request_id},
        )

    response.headers["X-Request-ID"] = request_id

    duration_ms = (_time.time() - request.state.start_time) * 1000
    log_response(
        endpoint=str(request.url.path),
        method=request.method,
        status_code=response.status_code,
        duration_ms=duration_ms,
        request_id=request_id,
    )

    if request.method in MUTATION_METHODS and response.status_code < 400:
        user_id = None
        if hasattr(request.state, "user"):
            user_id = getattr(request.state.user, "id", None)
        if user_id:
            await audit_middleware_dispatch(request, response, user_id=user_id, duration_ms=duration_ms)

    return response


@app.middleware("http")
async def cache_control_middleware(request: Request, call_next):
    response = await call_next(request)
    path = request.url.path

    if path.startswith("/static/") or path.startswith("/assets/"):
        response.headers["Cache-Control"] = "public, max-age=31536000, immutable"
    elif path.startswith("/health"):
        response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate"
    elif request.method == "GET":
        response.headers["Cache-Control"] = "private, max-age=60, stale-while-revalidate=300"
    else:
        response.headers["Cache-Control"] = "no-store, must-revalidate"

    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["X-XSS-Protection"] = "1; mode=block"

    return response


app.include_router(tasks.router, prefix="/api/v1/tasks", tags=["tasks"])
app.include_router(courses.router, prefix="/api/v1/courses", tags=["courses"])
app.include_router(goals.router, prefix="/api/v1/goals", tags=["goals"])
app.include_router(ideas.router, prefix="/api/v1/ideas", tags=["ideas"])
app.include_router(chat.router, prefix="/api/v1/chat", tags=["chat"])
app.include_router(projects.router, prefix="/api/v1/projects", tags=["projects"])
app.include_router(resources.router, prefix="/api/v1/resources", tags=["resources"])
app.include_router(opportunities.router, prefix="/api/v1/opportunities", tags=["opportunities"])
app.include_router(income.router, prefix="/api/v1/income", tags=["income"])
app.include_router(habits.router, prefix="/api/v1/habits", tags=["habits"])
app.include_router(sleep.router, prefix="/api/v1/sleep", tags=["sleep"])
app.include_router(time.router, prefix="/api/v1/time", tags=["time"])
app.include_router(automation.router, prefix="/api/v1/automation", tags=["automation"])
app.include_router(briefings.router, prefix="/api/v1/briefings", tags=["briefings"])
app.include_router(reviews.router, prefix="/api/v1/reviews", tags=["reviews"])
app.include_router(memory.router, prefix="/api/v1/memory", tags=["memory"])
app.include_router(roadmap.router, prefix="/api/v1/roadmap", tags=["roadmap"])
app.include_router(academics.router, prefix="/api/v1/academics", tags=["academics"])
app.include_router(videos.router, prefix="/api/v1/videos", tags=["videos"])
app.include_router(analytics.router, prefix="/api/v1/analytics", tags=["analytics"])
app.include_router(predictions.router, prefix="/api/v1/predictions", tags=["predictions"])
app.include_router(notifications.router, prefix="/api/v1/notifications", tags=["notifications"])
app.include_router(nlp.router, prefix="/api/v1/nlp", tags=["nlp"])
app.include_router(prompts.router, prefix="/api/v1/prompts", tags=["prompts"])
app.include_router(feedback.router, prefix="/api/v1/feedback", tags=["feedback"])
app.include_router(monitoring.router, prefix="/api/v1/monitoring", tags=["monitoring"])
app.include_router(data_export.router, prefix="/api/v1/data", tags=["data"])
app.include_router(feature_flags.router, prefix="/api/v1/feature-flags", tags=["feature_flags"])
app.include_router(auth.router, prefix="/api/v1/auth", tags=["auth"])
app.include_router(skills.router, prefix="/api/v1/skills", tags=["skills"])


@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    request_id = getattr(request.state, "request_id", str(uuid.uuid4()))
    logger.error(
        "Global unhandled exception",
        path=str(request.url.path),
        error=str(exc),
        error_type=type(exc).__name__,
        request_id=request_id,
    )
    return JSONResponse(
        status_code=500,
        content={
            "detail": "An unexpected error occurred",
            "error_code": "INTERNAL_ERROR",
            "request_id": request_id,
        },
        headers={"X-Request-ID": request_id},
    )


@app.get("/", tags=["system"])
async def root():
    return {
        "message": "Second Brain OS API is running",
        "version": settings.app_version,
        "environment": settings.environment,
        "docs": "/docs",
    }


@app.get("/health", tags=["system"])
async def health_check():
    total_endpoints = len(app.routes)
    return {
        "status": "healthy",
        "version": settings.app_version,
        "environment": settings.environment,
        "timestamp": _time.time(),
        "uptime_secs": _time.time() - getattr(app.state, "start_time", _time.time()),
        "endpoints_registered": total_endpoints,
    }


@app.get("/health/ready", tags=["system"])
async def readiness_check():
    deps = {
        "api": {"status": "ok"},
    }
    try:
        from config.core.supabase import get_supabase_client

        supabase = get_supabase_client()
        supabase.from_("users").select("count", count="exact").limit(1).execute()
        deps["supabase"] = {"status": "ok"}
    except Exception as e:
        deps["supabase"] = {"status": "error", "detail": str(e)}

    if settings.use_local_ai:
        try:
            import httpx

            async with httpx.AsyncClient(timeout=5) as client:
                resp = await client.get(f"{settings.ollama_base_url}/api/tags")
                if resp.status_code == 200:
                    deps["ollama"] = {"status": "ok"}
                else:
                    deps["ollama"] = {"status": "degraded"}
        except Exception as e:
            deps["ollama"] = {"status": "unavailable", "detail": str(e)}
    else:
        deps["claude_api"] = {"status": "configured" if settings.claude_api_key else "not_configured"}

    all_ok = all(d.get("status") in ("ok", "configured", "not_configured") for d in deps.values())
    overall = "healthy" if all_ok else "degraded"

    return {
        "status": overall,
        "version": settings.app_version,
        "dependencies": deps,
    }


@app.get("/health/live", tags=["system"])
async def liveness_check():
    return {"status": "alive"}
